### ISSUE TITLE
Command `AppConsoleCommandsSomeCommand` is not defined

### ISSUE THREAD

**Issue by faustbrian** [spatie/laravel-short-schedule#19] opened 2020-11-05 03:02 UTC
I recently started using this package to execute some commands that need to run very frequently but am experiencing a weird issue. My logs are getting spammed with the below message every time the command is executed. Now the weird issue, the command is actually executed which I can tell by the fact that a specific Job class shows up in Horizon every 10 seconds and is processed just fine.

## Error

```sh
[2020-11-05 02:52:40] local.ERROR: Command "AppConsoleCommandsSomeCommand" is not defined. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"AppConsoleCommandsSomeCommand\" is not defined. at /home/forge/project/vendor/symfony/console/Application.php:651)
[stacktrace]
#0 /home/forge/project/vendor/symfony/console/Application.php(230): Symfony\\Component\\Console\\Application->find()
#1 /home/forge/project/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#2 /home/forge/project/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#3 /home/forge/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#4 /home/forge/project/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#5 {main}
"} 
```

## Console/Kernel.php

```php
<?php

declare(strict_types=1);

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
use Spatie\ShortSchedule\ShortSchedule;

final class Kernel extends ConsoleKernel
{
    protected function schedule(Schedule $schedule)
    {
        //
    }

    protected function shortSchedule(ShortSchedule $shortSchedule)
    {
        $shortSchedule->command('some-command')->everySeconds(10);
    }

    protected function commands()
    {
        $this->load(__DIR__.'/Commands');
    }
}
```

What could be the cause of this issue? Running the same commands that are run via short-schedule with the native task runner of Laravel yields no errors but it doesn't execute them frequently enough which is why I need this package.

**Comment by freekmurze** [comment] 2020-11-05 10:59
I think it's something specific to your project, I can't reproduce this. Can you try it in a vanilla Laravel app.

Closing this for now as it works correctly in our project and tests. Feel free to PR a fix that would work for you.

**Closed by freekmurze** 2020-11-05 10:59 UTC

**Comment by faustbrian** [comment] 2020-11-05 11:59
I tried it in a fresh project and same issue but will figure it out. Thanks.
